### ISSUE TITLE
test failures in evaluator.dagger

### ISSUE THREAD

**Issue by revans2023** [cqframework/clinical-reasoning#219]
Pulled the latest today and still cannot get the "mvn package" to complete as there are test failures in evaluator.dagger:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] evaluator.shared 2.5.0-SNAPSHOT .................... SUCCESS [  1.950 s]
[INFO] evaluator.jaxb-deps ................................ SUCCESS [  3.514 s]
[INFO] evaluator.jackson-deps ............................. SUCCESS [  0.180 s]
[INFO] evaluator .......................................... SUCCESS [ 21.903 s]
[INFO] evaluator.fhir ..................................... SUCCESS [ 21.870 s]
[INFO] evaluator.fhir-npm ................................. SUCCESS [  5.038 s]
[INFO] evaluator.builder .................................. SUCCESS [  9.615 s]
[INFO] evaluator.library .................................. SUCCESS [ 21.800 s]
[INFO] evaluator.expression ............................... SUCCESS [ 20.391 s]
[INFO] evaluator.measure .................................. SUCCESS [  5.736 s]
[INFO] evaluator.measure-hapi ............................. SUCCESS [ 50.998 s]
[INFO] evaluator.dagger ................................... FAILURE [  4.482 s]
[INFO] evaluator.spring ................................... SKIPPED
[INFO] evaluator.cli ...................................... SKIPPED
[INFO] evaluator.content-test ............................. SKIPPED
[INFO] evaluator.activitydefinition ....................... SKIPPED
[INFO] evaluator.plandefinition 2.5.0-SNAPSHOT ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:48 min
[INFO] Finished at: 2022-12-27T10:55:16-05:00
[INFO] ------------------------------------------------------------------------

[INFO] Running TestSuite
[ERROR] Tests run: 4, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 1.114 s <<< FAILURE! - in TestSuite
[ERROR] canInstantiateDstu3(org.opencds.cqf.cql.evaluator.dagger.expression.ExpressionTests)  Time elapsed: 0.131 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/opencds/cqf/cql/evaluator/fhir/DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.expression.ExpressionTests.canInstantiateDstu3(ExpressionTests.java:17)
Caused by: java.lang.ClassNotFoundException: org.opencds.cqf.cql.evaluator.fhir.DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.expression.ExpressionTests.canInstantiateDstu3(ExpressionTests.java:17)

[ERROR] canInstantiateR4(org.opencds.cqf.cql.evaluator.dagger.expression.ExpressionTests)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/opencds/cqf/cql/evaluator/fhir/DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.expression.ExpressionTests.canInstantiateR4(ExpressionTests.java:25)
Caused by: java.lang.ClassNotFoundException: org.opencds.cqf.cql.evaluator.fhir.DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.expression.ExpressionTests.canInstantiateR4(ExpressionTests.java:25)

[ERROR] canInstantiateDstu3(org.opencds.cqf.cql.evaluator.dagger.library.LibraryTests)  Time elapsed: 0 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/opencds/cqf/cql/evaluator/fhir/DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.library.LibraryTests.canInstantiateDstu3(LibraryTests.java:18)
Caused by: java.lang.ClassNotFoundException: org.opencds.cqf.cql.evaluator.fhir.DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.library.LibraryTests.canInstantiateDstu3(LibraryTests.java:18)

[ERROR] canInstantiateR4(org.opencds.cqf.cql.evaluator.dagger.library.LibraryTests)  Time elapsed: 0 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/opencds/cqf/cql/evaluator/fhir/DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.library.LibraryTests.canInstantiateR4(LibraryTests.java:28)
Caused by: java.lang.ClassNotFoundException: org.opencds.cqf.cql.evaluator.fhir.DirectoryBundler_Factory
        at org.opencds.cqf.cql.evaluator.dagger.library.LibraryTests.canInstantiateR4(LibraryTests.java:28)

**Comment by revans2023** [comment]
I searched for solutions and I had to do "mvn clean install" and then double checked by running "mvn package" and now 2.5 builds

**Comment by revans2023** [comment]
documentation needs to be updated to run "mvn clean install" instead of "mvn package"
